import mongoose from "mongoose";
import Interview from "../models/interview.model.js";
import graph from "../graph/graph.js";
import AppError from "../utils/error.js";
import crypto from "node:crypto";
/*
 * ---------------------------------------------------------
 * Build Graph State
 * ---------------------------------------------------------
 * Converts MongoDB interview data into the state expected
 * by LangGraph.
 */
function buildGraphState(interview, extraState = {}) {
  return {
    userId: interview.userId.toString(),

    role: interview.role,
    experienceLevel: interview.experienceLevel,
    interviewLevel: interview.interviewLevel,
    interviewType: interview.interviewType,

    subjects: interview.subjects || [],
    techStack: interview.techStack || [],
    language: interview.language,

    difficulty: interview.difficulty,
    timeLimit: interview.timeLimit,
    questionCount: interview.questionCount,

    projectContext: interview.projectContext || null,

    status: interview.status,

    currentQuestionIndex: interview.currentQuestionIndex,
    currentQuestion: extraState.currentQuestion || null,
    currentAnswer: extraState.currentAnswer || "",
    currentEvaluation: extraState.currentEvaluation || null,

    questions: interview.questions || [],

    overallScore: interview.overallScore,
    sectionScores: interview.sectionScores,
    strengths: interview.strengths,
    weaknesses: interview.weaknesses,
    recommendations: interview.recommendations,
    summary: interview.summary,

    action: extraState.action || null,
    completed: false,
    error: null,
  };
}

/*
 * ---------------------------------------------------------
 * Validate Interview ID
 * ---------------------------------------------------------
 */
function validateInterviewId(interviewId) {
  if (!mongoose.Types.ObjectId.isValid(interviewId)) {
    throw new AppError("Invalid interview ID.", 400);
  }
}

/*
 * ---------------------------------------------------------
 * Get Interview Deadline
 * ---------------------------------------------------------
 */

function getInterviewDeadline(interview) {
  if (!interview.startedAt) {
    return null;
  }

  return new Date(
    new Date(interview.startedAt).getTime() +
      Number(interview.timeLimit || 30) * 60 * 1000,
  );
}

/*
 * ---------------------------------------------------------
 * Expire Interview Deadline
 * ---------------------------------------------------------
 */
async function expireInterviewIfNeeded(interview) {
  if (
    !interview.startedAt ||
    !["in-progress", "paused"].includes(interview.status)
  ) {
    return false;
  }

  const deadline = getInterviewDeadline(interview);

  if (!deadline || new Date() < deadline) {
    return false;
  }

  interview.status = "completed";
  interview.endedAt = new Date();
  interview.terminationReason = "time-limit";

  await interview.save();

  return true;
}

/*
 * ---------------------------------------------------------
 * Convert Graph Question
 * ---------------------------------------------------------
 */
function createQuestionRecord(question) {
  if (!question) {
    throw new AppError("Invalid question generated by interview engine.", 502);
  }

  return {
    questionId: crypto.randomUUID(),
    text: question.text,
    section: question.section,
    type: question.type || "primary",
    difficulty: question.difficulty,

    answer: "",
    askedAt: new Date(),
    submittedAt: null,

    evaluation: {
      score: 0,
      correctness: 0,
      clarity: 0,
      relevance: 0,
      communication: 0,
      feedback: "",
      strengths: [],
      weaknesses: [],
      betterAnswer: "",
      recommendations: [],
    },
  };
}

/*
 * ---------------------------------------------------------
 * START INTERVIEW
 * ---------------------------------------------------------
 */
export const startInterview = async (userId, interviewData) => {
  const interview = await Interview.create({
    userId,

    role: interviewData.role,
    experienceLevel: interviewData.experienceLevel,
    interviewLevel: interviewData.interviewLevel,
    interviewType: interviewData.interviewType,

    subjects: interviewData.subjects || [],
    language: interviewData.language || "english",

    difficulty: interviewData.difficulty || "easy",
    timeLimit: interviewData.timeLimit || 30,
    questionCount: interviewData.questionCount || 10,

    techStack: interviewData.techStack || [],
    projectContext: interviewData.projectContext || null,

    status: "created",
    startedAt: null,
    endedAt: null,
    terminationReason: null,
    currentQuestionIndex: 0,

    questions: [],
  });

  try {
    const graphState = buildGraphState(interview, {
      action: "start",
    });

    const result = await graph.invoke(graphState);

    const question = result.currentQuestion;

    if (!question) {
      throw new AppError("Failed to generate interview question.", 502);
    }

    interview.questions.push(createQuestionRecord(question));

    interview.currentQuestionIndex = 0;
    interview.status = "in-progress";

    interview.startedAt = new Date();
    interview.endedAt = null;
    interview.terminationReason = null;

    await interview.save();

    return {
      interviewId: interview._id,
      status: interview.status,
      currentQuestionIndex: interview.currentQuestionIndex,
      question: interview.questions[0],
    };
  } catch (error) {
    /*
     * The interview document remains available in `created`
     * state instead of silently disappearing.
     */
    if (error instanceof AppError) {
      throw error;
    }

    throw new AppError("Failed to start interview.", 502);
  }
};

/*
 * ---------------------------------------------------------
 * SUBMIT ANSWER
 * ---------------------------------------------------------
 */
export const submitAnswer = async (userId, interviewId, answer) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  const currentQuestion = interview.questions[interview.currentQuestionIndex];

  if (!currentQuestion) {
    throw new AppError("Current question not found.", 400);
  }

  if (currentQuestion.submittedAt) {
    throw new AppError(
      "Answer for this question has already been submitted.",
      400,
    );
  }

  /*
   * Save answer first.
   *
   * Important:
   * If the LLM fails, the candidate's answer is not lost.
   * submittedAt remains null so the answer can be retried.
   */
  currentQuestion.answer = answer;

  await interview.save();

  /*
   * Ask LangGraph to evaluate the answer.
   */
  try {
    const graphState = buildGraphState(interview, {
      action: "submit-answer",

      currentQuestion: {
        questionId: currentQuestion.questionId,
        text: currentQuestion.text,
        section: currentQuestion.section,
        type: currentQuestion.type,
        difficulty: currentQuestion.difficulty,
      },

      currentAnswer: answer,
    });

    const result = await graph.invoke(graphState);

    const evaluation = result.currentEvaluation;

    if (!evaluation) {
      throw new AppError("Failed to evaluate interview answer.", 502);
    }

    /*
     * Evaluation succeeded.
     * Now mark the answer as submitted.
     */
    currentQuestion.evaluation = evaluation;
    currentQuestion.submittedAt = new Date();

    await interview.save();

    return {
      interviewId: interview._id,
      questionId: currentQuestion.questionId,
      evaluation,
      currentQuestionIndex: interview.currentQuestionIndex,
    };
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }

    throw new AppError("Failed to evaluate interview answer.", 502);
  }
};

/*
 * ---------------------------------------------------------
 * NEXT QUESTION
 * ---------------------------------------------------------
 */
export const getNextQuestion = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  const currentQuestion = interview.questions[interview.currentQuestionIndex];

  /*
   * Candidate must answer the current question
   * before moving to the next one.
   */
  if (currentQuestion && !currentQuestion.submittedAt) {
    throw new AppError(
      "Submit the current answer before requesting the next question.",
      400,
    );
  }

  /*
   * All configured questions completed.
   */
  if (interview.questions.length >= interview.questionCount) {
    return completeInterview(userId, interviewId);
  }

  const nextQuestionIndex = interview.questions.length;

  try {
    const graphState = buildGraphState(interview, {
      action: "start",
    });

    graphState.currentQuestionIndex = nextQuestionIndex;

    const result = await graph.invoke(graphState);

    const question = result.currentQuestion;

    if (!question) {
      throw new AppError(
        "Failed to generate the next interview question.",
        502,
      );
    }

    interview.questions.push(createQuestionRecord(question));

    interview.currentQuestionIndex = nextQuestionIndex;

    await interview.save();

    return {
      interviewId: interview._id,
      currentQuestionIndex: nextQuestionIndex,
      question: interview.questions[nextQuestionIndex],
    };
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }

    throw new AppError("Failed to generate the next interview question.", 502);
  }
};

/*
 * ---------------------------------------------------------
 * COMPLETE INTERVIEW
 * ---------------------------------------------------------
 */
export const completeInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  if (interview.status !== "in-progress") {
    throw new AppError("Only an active interview can be completed.", 400);
  }

  /*
   * Every generated question must have an answer/evaluation
   * before the final summary is generated.
   */
  const incompleteQuestion = interview.questions.find(
    (question) => !question.submittedAt,
  );

  if (incompleteQuestion) {
    throw new AppError(
      "All interview questions must be answered before completion.",
      400,
    );
  }

  try {
    const graphState = buildGraphState(interview, {
      action: "summary",
    });

    const result = await graph.invoke(graphState);

    if (result.overallScore === undefined) {
      throw new AppError("Failed to generate interview summary.", 502);
    }

    interview.overallScore = result.overallScore ?? 0;
    interview.sectionScores = result.sectionScores || {};
    interview.strengths = result.strengths || [];
    interview.weaknesses = result.weaknesses || [];
    interview.recommendations = result.recommendations || [];
    interview.summary = result.summary || "";

    interview.status = "completed";
    interview.endedAt = new Date();
    interview.terminationReason = "completed";

    await interview.save();

    return {
      interviewId: interview._id,
      status: interview.status,
      overallScore: interview.overallScore,
      sectionScores: interview.sectionScores,
      strengths: interview.strengths,
      weaknesses: interview.weaknesses,
      recommendations: interview.recommendations,
      summary: interview.summary,
    };
  } catch (error) {
    if (error instanceof AppError) {
      throw error;
    }

    throw new AppError("Failed to complete interview.", 502);
  }
};

/*
 * ---------------------------------------------------------
 * GET INTERVIEW
 * ---------------------------------------------------------
 */
export const getInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  return interview;
};

/*
 * ---------------------------------------------------------
 * PAUSE INTERVIEW
 * ---------------------------------------------------------
 */
export const pauseInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  interview.status = "paused";

  await interview.save();

  return interview;
};

/*
 * ---------------------------------------------------------
 * RESUME INTERVIEW
 * ---------------------------------------------------------
 */
export const resumeInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  if (interview.status !== "paused") {
    throw new AppError("Only a paused interview can be resumed.", 400);
  }

  interview.status = "in-progress";

  await interview.save();

  return interview;
};

/*
 * ---------------------------------------------------------
 * QUIT INTERVIEW
 * ---------------------------------------------------------
 */
export const quitInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  if (interview.status === "completed" || interview.status === "abandoned") {
    throw new AppError("Interview is already closed.", 400);
  }

  interview.status = "abandoned";
  interview.endedAt = new Date();
  interview.terminationReason = "quit";

  await interview.save();

  return interview;
};

/*
 * ---------------------------------------------------------
 * INTERVIEW HISTORY
 * ---------------------------------------------------------
 */
export const getInterviewHistory = async (userId) => {
  return Interview.find({
    userId,
  }).sort({
    createdAt: -1,
  });
};

/*
 * ---------------------------------------------------------
 * DELETE INTERVIEW
 * ---------------------------------------------------------
 * Permanently deletes one interview belonging to the user.
 */
export const deleteInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  await Interview.deleteOne({
    _id: interviewId,
    userId,
  });

  return {
    interviewId,
  };
};

/*
 * ---------------------------------------------------------
 * ADD MORE QUESTIONS
 * ---------------------------------------------------------
 */
export const addMoreQuestions = async (userId, interviewId, count = 5) => {
  validateInterviewId(interviewId);

  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  /*
   * Zod already validates this at the API boundary.
   * Keep this defensive check because the service may also
   * be called internally.
   */

  const MAX_QUESTIONS = 50;

  if (interview.questionCount + count > MAX_QUESTIONS) {
    throw new AppError(
      `Interview cannot have more than ${MAX_QUESTIONS} questions.`,
      400,
    );
  }

  if (!Number.isInteger(count) || count < 1 || count > 20) {
    throw new AppError(
      "Question count must be an integer between 1 and 20.",
      400,
    );
  }

  interview.questionCount += count;

  await interview.save();

  return {
    interviewId: interview._id,
    questionCount: interview.questionCount,
  };
};


