import mongoose from "mongoose";
import crypto from "node:crypto";

import Interview from "../models/interview.model.js";

import graph from "../graph/graph.js";
import AppError from "../utils/error.js";

/*
 * =========================================================
 * CONSTANTS
 * =========================================================
 */

const INTERVIEW_COMPLETION_COST = 100;

const AUTH_SERVICE_URL =
  process.env.AUTH_SERVICE_URL || "http://localhost:8001";

/*
 * =========================================================
 * BUILD GRAPH STATE
 * =========================================================
 *
 * Converts the MongoDB interview document into the state
 * expected by LangGraph.
 *
 * currentQuestion / currentAnswer / currentEvaluation are
 * temporary values used by the feedback node.
 */
function buildGraphState(interview, extraState = {}) {
  return {
    userId: interview.userId.toString(),

    role: interview.role,

    experienceLevel: interview.experienceLevel,

    interviewLevel: interview.interviewLevel,

    interviewType: interview.interviewType,

    subjects: interview.subjects || [],

    techStack: interview.techStack || [],

    language: interview.language,

    difficulty: interview.difficulty,

    timeLimit: interview.timeLimit,

    questionCount: interview.questionCount,

    projectContext: interview.projectContext || null,

    status: interview.status,

    currentQuestionIndex: interview.currentQuestionIndex,

    currentQuestion: extraState.currentQuestion || null,

    currentAnswer: extraState.currentAnswer || "",

    currentEvaluation: extraState.currentEvaluation || null,

    questions:
      extraState.questions !== undefined
        ? extraState.questions
        : interview.questions || [],

    overallScore: interview.overallScore,

    sectionScores: interview.sectionScores,

    strengths: interview.strengths,

    weaknesses: interview.weaknesses,

    recommendations: interview.recommendations,

    summary: interview.summary,

    action: extraState.action || null,

    completed: false,

    error: null,
  };
}

/*
 * =========================================================
 * VALIDATE INTERVIEW ID
 * =========================================================
 */

function validateInterviewId(interviewId) {
  if (!mongoose.Types.ObjectId.isValid(interviewId)) {
    throw new AppError("Invalid interview ID.", 400);
  }
}

/*
 * =========================================================
 * GET INTERVIEW DEADLINE
 * =========================================================
 */

function getInterviewDeadline(interview) {
  if (!interview.startedAt) {
    return null;
  }

  return new Date(
    new Date(interview.startedAt).getTime() +
      Number(interview.timeLimit || 30) * 60 * 1000,
  );
}

/*
 * =========================================================
 * CREATE QUESTION RECORD
 * =========================================================
 *
 * The AI generates the question.
 *
 * MongoDB creates the interview-specific questionId so
 * the client can safely identify and submit any question.
 */
function createQuestionRecord(question) {
  if (!question) {
    throw new AppError("Invalid question generated by interview engine.", 502);
  }

  return {
    questionId: crypto.randomUUID(),

    text: question.text,

    section: question.section,

    type: question.type || "primary",

    difficulty: question.difficulty,

    answer: "",

    answerStatus: "not-submitted",

    askedAt: new Date(),

    submittedAt: null,

    evaluation: {
      score: 0,
      correctness: 0,
      clarity: 0,
      relevance: 0,
      communication: 0,
      feedback: "",
      strengths: [],
      weaknesses: [],
      betterAnswer: "",
      recommendations: [],
    },
  };
}

/*
 * =========================================================
 * GET USER INTERVIEW
 * =========================================================
 */

async function findUserInterview(userId, interviewId) {
  const interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  return interview;
}

/*
 * =========================================================
 * EVALUATE ONE QUESTION
 * =========================================================
 *
 * This is the ONLY place where an individual answer goes
 * through LangGraph/LLM evaluation.
 *
 * Navigation never calls this function.
 */
async function evaluateQuestion(interview, question) {
  if (!question) {
    throw new AppError("Interview question not found.", 400);
  }

  if (question.answerStatus === "submitted" || question.submittedAt) {
    return {
      alreadySubmitted: true,
      evaluation: question.evaluation,
    };
  }

  if (!question.answer || !question.answer.trim()) {
    throw new AppError("Answer is required before submission.", 400);
  }

  const graphState = buildGraphState(interview, {
    action: "submit-answer",

    currentQuestion: {
      questionId: question.questionId,
      text: question.text,
      section: question.section,
      type: question.type,
      difficulty: question.difficulty,
    },

    currentAnswer: question.answer,
  });

  const result = await graph.invoke(graphState);

  const evaluation = result.currentEvaluation;

  if (!evaluation) {
    throw new AppError("Failed to evaluate interview answer.", 502);
  }

  return {
    alreadySubmitted: false,
    evaluation,
  };
}

/*
 * =========================================================
 * MARK QUESTION SUBMITTED
 * =========================================================
 */

function markQuestionSubmitted(question, evaluation) {
  question.evaluation = evaluation;

  question.answerStatus = "submitted";

  question.submittedAt = new Date();
}

/*
 * =========================================================
 * ABANDON INTERVIEW ON SERVER ERROR
 * =========================================================
 *
 * Already submitted questions remain preserved.
 *
 * No completion.
 * No coin deduction.
 */
async function abandonForServerError(interview) {
  /*
   * Never abandon an interview after its payment has
   * already been charged.
   *
   * The caller should recover/finalize such an interview
   * instead of converting it into a failed interview.
   */
  if (
    interview.paymentStatus === "charged" ||
    interview.paymentStatus === "charging"
  ) {
    throw new AppError(
      "Interview payment is already being processed. Finalization must continue.",
      503,
    );
  }

  interview.status = "abandoned";

  interview.endedAt = new Date();

  interview.terminationReason = "server-error";

  interview.finalizationKey = null;

  await interview.save();
}

function generateFallbackReport(interview) {
  const evaluatedQuestions = interview.questions.filter(
    (question) =>
      question.answerStatus === "submitted" &&
      question.submittedAt &&
      question.evaluation,
  );

  /*
   * No answers were evaluated.
   */
  if (evaluatedQuestions.length === 0) {
    return {
      overallScore: 0,
      sectionScores: {},
      strengths: [],
      weaknesses: ["No interview answers were evaluated."],
      recommendations: [
        "Attempt the interview questions to receive performance feedback.",
        "Provide complete answers before submitting future interviews.",
        "Focus on explaining your reasoning clearly.",
        "Review the topics covered in the interview.",
        "Practice answering technical questions under time constraints.",
      ],
      summary:
        "The interview was submitted without any evaluated answers. The unanswered questions were preserved as Not Answered and were not included in the performance evaluation.",
    };
  }

  /*
   * Calculate fallback overall score from already
   * evaluated answers.
   */
  const scores = evaluatedQuestions
    .map((question) => Number(question.evaluation?.score))
    .filter((score) => Number.isFinite(score));

  const overallScore =
    scores.length > 0
      ? Number(
          (
            scores.reduce((total, score) => total + score, 0) / scores.length
          ).toFixed(2),
        )
      : 0;

  /*
   * Calculate section scores only from sections
   * that actually have evaluated answers.
   */
  const sectionData = {};

  for (const question of evaluatedQuestions) {
    const section = question.section;
    const score = Number(question.evaluation?.score);

    if (!section || !Number.isFinite(score)) {
      continue;
    }

    if (!sectionData[section]) {
      sectionData[section] = [];
    }

    sectionData[section].push(score);
  }

  const sectionScores = Object.fromEntries(
    Object.entries(sectionData).map(([section, values]) => [
      section,
      Number(
        (
          values.reduce((total, score) => total + score, 0) / values.length
        ).toFixed(2),
      ),
    ]),
  );

  /*
   * Reuse information already produced by individual
   * answer evaluations.
   */
  const strengths = [
    ...new Set(
      evaluatedQuestions.flatMap(
        (question) => question.evaluation?.strengths || [],
      ),
    ),
  ].slice(0, 5);

  const weaknesses = [
    ...new Set(
      evaluatedQuestions.flatMap(
        (question) => question.evaluation?.weaknesses || [],
      ),
    ),
  ].slice(0, 5);

  const recommendations = [
    ...new Set(
      evaluatedQuestions.flatMap(
        (question) => question.evaluation?.recommendations || [],
      ),
    ),
  ].slice(0, 5);

  /*
   * Keep the report structure populated even when
   * individual evaluations contain fewer items.
   */
  while (strengths.length < 3) {
    strengths.push("Continue building consistency in technical explanations.");
  }

  while (weaknesses.length < 3) {
    weaknesses.push("Continue improving depth and clarity of explanations.");
  }

  while (recommendations.length < 5) {
    recommendations.push(
      "Practice explaining technical concepts clearly and concisely.",
    );
  }

  return {
    overallScore,
    sectionScores,
    strengths,
    weaknesses,
    recommendations,
    summary:
      `The interview contained ${evaluatedQuestions.length} evaluated ` +
      `answer(s). The remaining unanswered questions were preserved as ` +
      `"Not Answered" and were not included in the performance evaluation.`,
  };
}

/*
 * =========================================================
 * GENERATE FINAL SUMMARY
 * =========================================================
 */

async function generateInterviewSummary(interview) {
  try {
    const summaryQuestions = interview.questions.map((question) => ({
      questionId: question.questionId,
      text: question.text,
      section: question.section,
      difficulty: question.difficulty,
      answerStatus: question.answerStatus,
      evaluation: question.evaluation,
    }));

    const graphState = buildGraphState(interview, {
      action: "summary",
      questions: summaryQuestions,
    });

    const result = await graph.invoke(graphState);

    if (result.overallScore === undefined) {
      throw new Error("Summary result is incomplete.");
    }

    return {
      overallScore: result.overallScore ?? 0,
      sectionScores: result.sectionScores || {},
      strengths: result.strengths || [],
      weaknesses: result.weaknesses || [],
      recommendations: result.recommendations || [],
      summary: result.summary || "",
    };
  } catch (error) {
    /*
     * Summary LLM failure must NOT prevent interview
     * completion.
     *
     * Example:
     * Groq 429 / timeout / malformed summary response
     *
     * We already have individual answer evaluations,
     * so create a deterministic fallback report from
     * those evaluations.
     */
    console.error("Summary generation failed. Using fallback report:", error);

    return generateFallbackReport(interview);
  }
}

/*
 * =========================================================
 * DEDUCT INTERVIEW COINS THROUGH AUTH SERVICE
 * =========================================================
 *
 * Interview Service does not access the Auth User model
 * directly.
 *
 * Auth Service owns:
 * - User
 * - coins
 * - coin deduction
 */

async function getUserBalance(userId) {
  let response;

  try {
    response = await fetch(`${AUTH_SERVICE_URL}/internal/user-balance`, {
      method: "POST",

      headers: {
        "Content-Type": "application/json",
        "x-user-id": userId.toString(),
      },
    });
  } catch (error) {
    console.error("Auth Service balance request failed:", error);

    throw new AppError(
      "Unable to verify your interview balance right now. Please try again.",
      503,
    );
  }

  let data = null;

  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    throw new AppError(
      data?.message || "Unable to verify your interview balance.",
      response.status >= 500 ? 503 : response.status,
    );
  }

  return Number(data?.coins) || 0;
}

async function deductInterviewCoins(userId, interviewId) {
  let response;

  try {
    response = await fetch(`${AUTH_SERVICE_URL}/internal/user-coins`, {
      method: "POST",

      headers: {
        "Content-Type": "application/json",
        "x-user-id": userId.toString(),
      },

      body: JSON.stringify({
        coin: INTERVIEW_COMPLETION_COST,
        action: "interview-completion",
        transactionId: `interview:${interviewId.toString()}:completion`,
      }),
    });
  } catch (error) {
    console.error("Auth Service coin request failed:", error);

    throw new AppError(
      "Unable to charge interview coins right now. Please try again.",
      503,
    );
  }

  let data = null;

  try {
    data = await response.json();
  } catch {
    data = null;
  }

  /*
   * Auth Service returned a business error.
   *
   * Example:
   * - insufficient coins
   * - user not found
   */
  if (!response.ok) {
    const message = data?.message || "Unable to charge interview coins.";

    /*
     * Preserve expected 4xx business errors.
     *
     * submitInterview() will NOT abandon the interview
     * automatically for these errors.
     */
    if (response.status >= 400 && response.status < 500) {
      throw new AppError(message, response.status);
    }

    throw new AppError(message, 502);
  }

  if (!data?.success) {
    throw new AppError("Unable to charge interview coins.", 502);
  }

  return data;
}

/*
 * =========================================================
 * FINALIZE + CHARGE
 * =========================================================
 *
 * IMPORTANT:
 *
 * Interview Service requests the coin deduction from the
 * Auth Service before marking the interview as completed.
 *
 * The Auth Service owns the user's coin balance and handles
 * the deduction/idempotency for the interview transaction.
 */
async function finalizeInterviewWithCharge(
  userId,
  interviewId,
  report,
  terminationReason = "completed",
  lockAlreadyAcquired = false,
) {
  /*
   * ---------------------------------------------------------
   * Load the interview.
   * ---------------------------------------------------------
   */
  let interview = await Interview.findOne({
    _id: interviewId,
    userId,
  });

  if (!interview) {
    throw new AppError("Interview not found.", 404);
  }

  /*
   * ---------------------------------------------------------
   * Idempotent retry.
   *
   * If another request already completed the interview,
   * return the existing report.
   *
   * Do NOT charge again here.
   * ---------------------------------------------------------
   */
  if (interview.status === "completed" && interview.finalizedAt) {
    return interview;
  }

  /*
   * ---------------------------------------------------------
   * Acquire finalization lock atomically.
   * ---------------------------------------------------------
   *
   * Only one request can move this interview into the
   * finalization flow.
   *
   * Another simultaneous request will fail to acquire the
   * lock and must retry/read the latest interview state.
   * ---------------------------------------------------------
   */
  if (!lockAlreadyAcquired) {
    const finalizationKey = `finalize:${interviewId.toString()}`;

    const lockedInterview = await Interview.findOneAndUpdate(
      {
        _id: interviewId,
        userId,
        status: "in-progress",
        $or: [
          { finalizationKey: null },
          { finalizationKey: { $exists: false } },
        ],
      },
      {
        $set: {
          finalizationKey,
        },
      },
      {
        new: true,
      },
    );

    if (!lockedInterview) {
      const latestInterview = await Interview.findOne({
        _id: interviewId,
        userId,
      });

      if (latestInterview?.status === "completed") {
        return latestInterview;
      }

      /*
       * Payment may already have succeeded in a previous
       * finalization attempt. In that case, do not try to
       * charge again. Allow this retry to continue finalization.
       */
      if (latestInterview?.paymentStatus === "charged") {
        latestInterview.finalizationKey = finalizationKey;

        await latestInterview.save();

        interview = latestInterview;
      } else {
        throw new AppError(
          "Interview finalization is already in progress. Please retry.",
          409,
        );
      }
    } else {
      interview = lockedInterview;
    }
  }

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }
  /*
   * ---------------------------------------------------------
   * Payment lifecycle.
   * ---------------------------------------------------------
   *
   * If this interview was already charged during a previous
   * attempt, NEVER call Auth Service again.
   *
   * This makes finalization retry-safe.
   * ---------------------------------------------------------
   */
  if (interview.paymentStatus !== "charged") {
    /*
     * Reuse the existing transaction ID when the interview
     * is already in "charging" state.
     *
     * This guarantees that retries belong to the same
     * payment transaction.
     */
    const paymentTransactionId =
      interview.paymentTransactionId ||
      `interview:${interviewId.toString()}:completion`;

    interview.paymentStatus = "charging";
    interview.paymentTransactionId = paymentTransactionId;

    await interview.save();

    /*
     * Auth Service owns the actual coin deduction and
     * transaction idempotency.
     */
    try {
      await deductInterviewCoins(userId, interviewId);

      /*
       * Coins successfully deducted.
       */
      interview.paymentStatus = "charged";
    } catch (error) {
      /*
       * A 4xx response represents a business-level payment
       * failure such as insufficient coins.
       *
       * No successful deduction happened, so the interview
       * must NOT remain stuck in "charging".
       */
      if (
        error instanceof AppError &&
        error.statusCode >= 400 &&
        error.statusCode < 500
      ) {
        interview.paymentStatus = "not-charged";

        interview.paymentTransactionId = null;

        interview.finalizationKey = null;

        await interview.save();
      }

      throw error;
    }

    /*
     * Coins successfully deducted.
     */
    interview.paymentStatus = "charged";
  }

  /*
   * ---------------------------------------------------------
   * Payment is now complete.
   *
   * From this point onward, finalization must not perform
   * another payment operation.
   * ---------------------------------------------------------
   */
  if (interview.paymentStatus === "charged") {
    interview.paymentTransactionId =
      interview.paymentTransactionId ||
      `interview:${interviewId.toString()}:completion`;
  }

  /*
   * ---------------------------------------------------------
   * Save final report.
   * ---------------------------------------------------------
   */
  interview.overallScore = report.overallScore;

  interview.sectionScores = report.sectionScores;

  interview.strengths = report.strengths;

  interview.weaknesses = report.weaknesses;

  interview.recommendations = report.recommendations;

  interview.summary = report.summary;

  interview.status = "completed";

  interview.endedAt = new Date();

  interview.terminationReason = terminationReason;

  interview.finalizedAt = new Date();

  /*
   * ---------------------------------------------------------
   * Finalization completed successfully.
   *
   * The lock is no longer needed because the interview is
   * now permanently completed.
   * ---------------------------------------------------------
   */
  interview.finalizationKey = null;

  await interview.save();

  return interview;
}

/*
 * =========================================================
 * START INTERVIEW
 * =========================================================
 *
 * IMPORTANT:
 *
 * All questions are generated in ONE interview-start
 * operation.
 *
 * No question is generated from Next/Previous.
 */
export const startInterview = async (userId, interviewData) => {
  const questionCount = Number(interviewData.questionCount || 10);

  const balance = await getUserBalance(userId);

  if (balance < INTERVIEW_COMPLETION_COST) {
    throw new AppError(
      `Not enough balance. You need at least ${INTERVIEW_COMPLETION_COST} coins to start the interview.`,
      400,
    );
  }

  const interview = await Interview.create({
    userId,

    role: interviewData.role,

    experienceLevel: interviewData.experienceLevel,

    interviewLevel: interviewData.interviewLevel,

    interviewType: interviewData.interviewType,

    subjects: interviewData.subjects || [],

    language: interviewData.language || "english",

    difficulty: interviewData.difficulty || "easy",

    timeLimit: interviewData.timeLimit || 30,

    questionCount,

    techStack: interviewData.techStack || [],

    projectContext: interviewData.projectContext || null,

    status: "created",

    startedAt: null,

    endedAt: null,

    terminationReason: null,

    currentQuestionIndex: 0,

    questions: [],
  });

  try {
    const graphState = buildGraphState(interview, {
      action: "start",
    });

    const result = await graph.invoke(graphState);

    if (!result?.questions || result.questions.length === 0) {
      throw new AppError("Failed to generate interview questions.", 502);
    }

    /*
     * The model/prompt must generate exactly the configured
     * number of questions.
     */
    if (result.questions.length !== questionCount) {
      throw new AppError(
        "Generated question count does not match the interview configuration.",
        502,
      );
    }

    const questionRecords = result.questions.map(createQuestionRecord);

    interview.questions = questionRecords;

    interview.currentQuestionIndex = 0;

    interview.status = "in-progress";

    interview.startedAt = new Date();

    interview.endedAt = null;

    interview.terminationReason = null;

    await interview.save();

    return {
      interviewId: interview._id,

      status: interview.status,

      currentQuestionIndex: interview.currentQuestionIndex,

      questionCount: interview.questions.length,

      questions: interview.questions,
    };
  } catch (error) {
    /*
     * Question generation failed after the interview
     * document was created.
     *
     * Mark the interview as failed so we don't leave
     * an orphaned "created" interview in the database.
     *
     * No coins are charged during interview start.
     */
    try {
      interview.status = "failed";
      interview.endedAt = new Date();
      interview.terminationReason = "server-error";

      await interview.save();
    } catch (updateError) {
      console.error("Failed to mark interview start as failed:", updateError);
    }

    if (error instanceof AppError) {
      throw error;
    }

    throw new AppError("Failed to start interview.", 502);
  }
};

/*
 * =========================================================
 * BEGIN INTERVIEW
 * =========================================================
 */
export const beginInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await findUserInterview(userId, interviewId);

  if (interview.status !== "created") {
    throw new AppError("Interview cannot be started.", 400);
  }
  
  interview.status = "created";

  interview.startedAt = null;

  interview.endedAt = null;

  interview.terminationReason = null;

  await interview.save();

  return interview;
};

/*
 * =========================================================
 * NEXT QUESTION
 * =========================================================
 *
 * Navigation ONLY.
 *
 * No LLM call.
 */
export const getNextQuestion = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await findUserInterview(userId, interviewId);

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  const deadline = getInterviewDeadline(interview);

  if (deadline && new Date() >= deadline) {
    await expireInterviewIfNeeded(interview);

    throw new AppError("Interview time has expired.", 400);
  }

  const nextIndex = interview.currentQuestionIndex + 1;

  if (nextIndex >= interview.questions.length) {
    return interview;
  }

  interview.currentQuestionIndex = nextIndex;

  await interview.save();

  return interview;
};

/*
 * =========================================================
 * PREVIOUS QUESTION
 * =========================================================
 *
 * Navigation ONLY.
 *
 * No LLM call.
 */
export const getPreviousQuestion = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await findUserInterview(userId, interviewId);

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  const deadline = getInterviewDeadline(interview);

  if (deadline && new Date() >= deadline) {
    await expireInterviewIfNeeded(interview);

    throw new AppError("Interview time has expired.", 400);
  }

  const previousIndex = interview.currentQuestionIndex - 1;

  if (previousIndex < 0) {
    return interview;
  }

  interview.currentQuestionIndex = previousIndex;

  await interview.save();

  return interview;
};

/*
 * =========================================================
 * JUMP TO QUESTION
 * =========================================================
 *
 * Navigation only.
 *
 * Keeps frontend question-card navigation
 * synchronized with the persisted interview index.
 */
export const jumpToQuestion = async (userId, interviewId, index) => {
  validateInterviewId(interviewId);

  const interview = await findUserInterview(userId, interviewId);

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  const deadline = getInterviewDeadline(interview);

  if (deadline && new Date() >= deadline) {
    await expireInterviewIfNeeded(interview);

    throw new AppError("Interview time has expired.", 400);
  }

  const targetIndex = Number(index);

  if (
    !Number.isInteger(targetIndex) ||
    targetIndex < 0 ||
    targetIndex >= interview.questions.length
  ) {
    throw new AppError("Invalid question index.", 400);
  }

  interview.currentQuestionIndex = targetIndex;

  await interview.save();

  return interview;
};
/*
 * =========================================================
 * SUBMIT ENTIRE INTERVIEW
 * =========================================================
 *
 * This is the final submission.
 *
 * Already submitted questions:
 *     NEVER evaluated again.
 *
 * Remaining questions:
 *     evaluated one by one.
 *
 * If any remaining evaluation fails:
 *     interview becomes abandoned/server-error.
 *
 * Already successful evaluations remain saved.
 */
export const submitInterview = async (
  userId,
  interviewId,
  draftAnswers = {},
) => {
  validateInterviewId(interviewId);

  let interview = await findUserInterview(userId, interviewId);

  /*
   * -------------------------------------------------------
   * Already completed
   * -------------------------------------------------------
   *
   * Final submission is idempotent.
   *
   * If the frontend submits again after completion,
   * return the existing report instead of throwing
   * "Interview is not active."
   */
  if (interview.status === "completed" && interview.finalizedAt) {
    return {
      interviewId: interview._id,
      status: interview.status,
      terminationReason: interview.terminationReason,
      overallScore: interview.overallScore,
      sectionScores: interview.sectionScores,
      strengths: interview.strengths,
      weaknesses: interview.weaknesses,
      recommendations: interview.recommendations,
      summary: interview.summary,
      alreadyFinalized: true,
    };
  }

  if (interview.status !== "in-progress") {
    throw new AppError("Interview is not active.", 400);
  }

  /*
   * -------------------------------------------------------
   * Persist the current frontend draft before finalization.
   *
   * This is intentionally NOT submitAnswer().
   *
   * Timer expiry must be able to capture the textarea draft
   * without passing through the normal active-answer endpoint.
   * -------------------------------------------------------
   */
  if (draftAnswers && typeof draftAnswers === "object") {
    for (const question of interview.questions) {
      if (question.answerStatus === "submitted" || question.submittedAt) {
        continue;
      }

      const draftAnswer = draftAnswers[question.questionId];

      if (typeof draftAnswer === "string") {
        question.answer = draftAnswer.trim();
      }
    }

    await interview.save();
  }

  /*
   * -------------------------------------------------------
   * Time check
   * -------------------------------------------------------
   */
  const deadline = getInterviewDeadline(interview);

  const isTimeExpired = deadline && new Date() >= deadline;

  try {
    /*
     * -----------------------------------------------------
     * Evaluate ONLY answered questions.
     *
     * Unanswered questions remain:
     *
     * answerStatus = "not-submitted"
     * submittedAt = null
     *
     * They are NOT sent to the LLM.
     * -----------------------------------------------------
     */
    const finalizationKey = `finalize:${interviewId.toString()}`;

    const lockedInterview = await Interview.findOneAndUpdate(
      {
        _id: interviewId,
        userId,
        status: "in-progress",
        $or: [
          { finalizationKey: null },
          { finalizationKey: { $exists: false } },
        ],
      },
      {
        $set: {
          finalizationKey,
        },
      },
      {
        new: true,
      },
    );

    if (!lockedInterview) {
      const latestInterview = await Interview.findOne({
        _id: interviewId,
        userId,
      });

      if (latestInterview?.status === "completed") {
        return {
          status: "completed",
          interview: latestInterview,
          report: latestInterview.report,
          coinsCharged: INTERVIEW_COMPLETION_COST,
        };
      }

      throw new AppError(
        "Interview is already being finalized. Please retry.",
        409,
      );
    }

    interview = lockedInterview;

    const pendingAnsweredQuestions = interview.questions.filter(
      (question) =>
        question.answerStatus !== "submitted" &&
        !question.submittedAt &&
        typeof question.answer === "string" &&
        question.answer.trim(),
    );

    for (const question of pendingAnsweredQuestions) {
      const { evaluation } = await evaluateQuestion(interview, question);

      markQuestionSubmitted(question, evaluation);

      /*
       * Persist after every successful evaluation.
       *
       * If a later question fails, earlier successful
       * evaluations remain preserved.
       */
      await interview.save();
    }

    /*
     * -----------------------------------------------------
     * Reload latest interview before report generation.
     * -----------------------------------------------------
     */
    interview = await Interview.findOne({
      _id: interviewId,
      userId,
    });

    if (!interview) {
      throw new AppError("Interview not found.", 404);
    }

    /*
     * -----------------------------------------------------
     * IMPORTANT:
     *
     * We DO NOT require every question to be submitted.
     *
     * Example:
     *
     * Q1 submitted
     * Q2 submitted
     * Q3 not answered
     * Q4 not answered
     * Q5 not answered
     *
     * This is a valid completed interview.
     * -----------------------------------------------------
     */

    /*
     * -----------------------------------------------------
     * Generate final report.
     *
     * If the LLM summary fails, generateInterviewSummary()
     * automatically creates a deterministic fallback report.
     * -----------------------------------------------------
     */
    const evaluatedAnswerCount = interview.questions.filter(
      (question) =>
        question.answerStatus === "submitted" &&
        question.submittedAt &&
        question.evaluation,
    ).length;

    /*
     * If the candidate never attempted any answer,
     * the interview is abandoned.
     *
     * It must NOT:
     * - generate a report
     * - charge interview coins
     * - become a completed interview
     * - appear as completed history
     */
    if (evaluatedAnswerCount === 0) {
      interview.status = "abandoned";

      interview.terminationReason = isTimeExpired ? "time-limit" : "no-answers";

      interview.endedAt = new Date();

      /*
       * No answer means no payment.
       * Release the finalization lock before closing
       * the interview as abandoned.
       */
      interview.finalizationKey = null;

      await interview.save();

      return {
        interviewId: interview._id,
        status: "abandoned",
        terminationReason: interview.terminationReason,
        coinsCharged: 0,
      };
    }

    const report = await generateInterviewSummary(interview);

    /*
     * -----------------------------------------------------
     * Finalize interview + charge coins.
     * -----------------------------------------------------
     */
    const terminationReason = isTimeExpired ? "time-limit" : "completed";

    const finalizedInterview = await finalizeInterviewWithCharge(
      userId,
      interviewId,
      report,
      terminationReason,
      true,
    );

    return {
      interviewId: finalizedInterview._id,
      status: finalizedInterview.status,
      terminationReason: finalizedInterview.terminationReason,
      overallScore: finalizedInterview.overallScore,
      sectionScores: finalizedInterview.sectionScores,
      strengths: finalizedInterview.strengths,
      weaknesses: finalizedInterview.weaknesses,
      recommendations: finalizedInterview.recommendations,
      summary: finalizedInterview.summary,
      coinsCharged: INTERVIEW_COMPLETION_COST,
      alreadyFinalized: false,
    };
  } catch (error) {
    console.error("FINAL SUBMIT ROOT ERROR:", error);
    /*
     * -----------------------------------------------------
     * Business errors
     * -----------------------------------------------------
     *
     * Insufficient coins, invalid state, etc. should not
     * automatically turn the interview into server-error.
     */
    if (
      error instanceof AppError &&
      error.statusCode >= 400 &&
      error.statusCode < 500
    ) {
      throw error;
    }

    /*
     * -----------------------------------------------------
     * Actual evaluation/server failure
     * -----------------------------------------------------
     *
     * Successful evaluations remain preserved.
     *
     * IMPORTANT:
     * Summary failures are already handled by the fallback
     * report and therefore should normally never reach here.
     */
    try {
      const currentInterview = await Interview.findOne({
        _id: interviewId,
        userId,
      });

      /*
       * -------------------------------------------------------
       * Payment is already charged.
       *
       * NEVER abandon the interview.
       *
       * A later retry must finish the interview without
       * charging the user again.
       * -------------------------------------------------------
       */
      if (currentInterview?.paymentStatus === "charged") {
        throw new AppError(
          "Your interview payment was processed, but finalization is still pending. Please retry.",
          503,
        );
      }

      /*
       * -------------------------------------------------------
       * Payment is currently being processed.
       *
       * Do NOT abandon the interview.
       *
       * The same payment transaction can safely be retried.
       * -------------------------------------------------------
       */
      if (currentInterview?.paymentStatus === "charging") {
        /*
         * Payment may have succeeded remotely.
         * Keep paymentStatus = "charging" and the same
         * transaction ID, but release the interview lock so
         * the next retry can continue the same idempotent
         * payment transaction.
         */
        currentInterview.finalizationKey = null;

        await currentInterview.save();

        throw new AppError(
          "Your interview is still being finalized. Please retry.",
          503,
        );
      }

      /*
       * -------------------------------------------------------
       * No payment has been processed.
       *
       * A genuine server-side failure can safely abandon the
       * interview without charging coins.
       * -------------------------------------------------------
       */
      if (currentInterview && currentInterview.status === "in-progress") {
        currentInterview.finalizationKey = null;

        await abandonForServerError(currentInterview);
      }
    } catch (recoveryError) {
      if (recoveryError instanceof AppError) {
        throw recoveryError;
      }

      console.error(
        "Failed to process interview finalization recovery:",
        recoveryError,
      );
    }

    throw new AppError(
      "We couldn't complete your interview due to a server error. Your interview has been ended without charging coins.",
      502,
    );
  }
};

/*
 * =========================================================
 * EXPIRE INTERVIEW
 * =========================================================
 * Backend is the source of truth for time.
 *
 * When the deadline is reached:
 * - answered pending questions are evaluated
 * - unanswered questions remain Not Answered
 * - an interview with no evaluated answers is abandoned
 * - an interview with evaluated answers is finalized and charged
 */

async function expireInterviewIfNeeded(interview) {
  if (!interview.startedAt || interview.status !== "in-progress") {
    return false;
  }

  const deadline = getInterviewDeadline(interview);

  if (!deadline || new Date() < deadline) {
    return false;
  }

  /*
   * The interview has reached its time limit strictly according
   * to the original deadline calculated from startedAt.
   */
  try {
    /*
     * -----------------------------------------------------
     * Acquire the finalization lock BEFORE evaluating any
     * pending answers.
     *
     * This prevents timer expiry and manual final submission
     * from evaluating/finalizing the same interview concurrently.
     * -----------------------------------------------------
     */
    const finalizationKey = `finalize:${interview._id.toString()}`;

    const lockedInterview = await Interview.findOneAndUpdate(
      {
        _id: interview._id,
        status: "in-progress",
        $or: [
          { finalizationKey: null },
          { finalizationKey: { $exists: false } },
        ],
      },
      {
        $set: {
          finalizationKey,
        },
      },
      {
        new: true,
      },
    );

    if (!lockedInterview) {
      const latestInterview = await Interview.findById(interview._id);

      /*
       * Another request already completed the interview.
       */
      if (latestInterview?.status === "completed") {
        return true;
      }

      /*
       * Another request is already finalizing it.
       *
       * Do not evaluate the same answers again.
       */
      return true;
    }

    interview = lockedInterview;

    /*
     * -----------------------------------------------------
     * Evaluate only answered questions that have not
     * already been submitted.
     *
     * Unanswered questions remain Not Answered.
     * -----------------------------------------------------
     */
    const pendingQuestions = interview.questions.filter(
      (question) =>
        question.answerStatus !== "submitted" &&
        !question.submittedAt &&
        typeof question.answer === "string" &&
        question.answer.trim(),
    );

    for (const question of pendingQuestions) {
      const { evaluation } = await evaluateQuestion(interview, question);

      markQuestionSubmitted(question, evaluation);

      // Persist every successful evaluation immediately.
      // If a later question fails, earlier evaluations remain saved.
      await interview.save();
    }

    /*
     * -----------------------------------------------------
     * Reload latest data.
     * -----------------------------------------------------
     */
    const latestInterview = await Interview.findById(interview._id);

    if (!latestInterview) {
      throw new AppError("Interview not found.", 404);
    }

    /*
     * -----------------------------------------------------
     * Generate report.
     * -----------------------------------------------------
     */
    const evaluatedAnswerCount = latestInterview.questions.filter(
      (question) =>
        question.answerStatus === "submitted" &&
        question.submittedAt &&
        question.evaluation,
    ).length;

    /*
     * -----------------------------------------------------
     * Timer expired without any attempted answer.
     *
     * This interview must:
     * - NOT generate a report
     * - NOT charge coins
     * - NOT become completed
     * - NOT appear as completed history
     * -----------------------------------------------------
     */
    if (evaluatedAnswerCount === 0) {
      latestInterview.status = "abandoned";

      latestInterview.terminationReason = "time-limit";

      latestInterview.endedAt = new Date();

      /*
       * No answer means no payment.
       * Release the finalization lock before closing
       * the interview as abandoned.
       */
      latestInterview.finalizationKey = null;

      await latestInterview.save();

      return true;
    }

    const report = await generateInterviewSummary(latestInterview);

    /*
     * -----------------------------------------------------
     * Finalize + charge exactly once.
     * -----------------------------------------------------
     */
    await finalizeInterviewWithCharge(
      latestInterview.userId,
      latestInterview._id,
      report,
      "time-limit",
      true,
    );

    return true;
  } catch (error) {
    /*
     * Time-limit processing failed.
     *
     * Preserve whatever was already successfully evaluated.
     *
     * Business errors such as insufficient coins are propagated
     * to the caller and are NOT converted into server-error
     * abandonment.
     *
     * Actual evaluation/server failures abandon the interview
     * without charging coins.
     */
    if (
      error instanceof AppError &&
      error.statusCode >= 400 &&
      error.statusCode < 500
    ) {
      throw error;
    }

    try {
      const currentInterview = await Interview.findById(interview._id);

      if (currentInterview && currentInterview.status === "in-progress") {
        /*
         * Payment has already been processed.
         *
         * NEVER abandon the interview.
         * A later retry must finish finalization without
         * charging the user again.
         */
        if (currentInterview.paymentStatus === "charged") {
          currentInterview.finalizationKey = null;

          await currentInterview.save();

          return true;
        }

        /*
         * Payment may still be processing remotely.
         *
         * Do NOT abandon the interview.
         * Release the lock so a later retry can continue
         * the same idempotent payment transaction.
         */
        if (currentInterview.paymentStatus === "charging") {
          currentInterview.finalizationKey = null;

          await currentInterview.save();

          return true;
        }

        currentInterview.finalizationKey = null;

        await abandonForServerError(currentInterview);
      }
    } catch (abandonError) {
      console.error("Failed to abandon expired interview:", abandonError);
    }

    return true;
  }
}

/*
 * =========================================================
 * GET INTERVIEW
 * =========================================================
 */

export const getInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await findUserInterview(userId, interviewId);

  /*
   * If the request happens after the deadline,
   * process expiration before returning state.
   */
  if (interview.status === "in-progress") {
    await expireInterviewIfNeeded(interview);
  }

  return Interview.findOne({
    _id: interviewId,
    userId,
  });
};

/*
 * =========================================================
 * QUIT INTERVIEW
 * =========================================================
 */

export const quitInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await findUserInterview(userId, interviewId);

  if (interview.status === "completed" || interview.status === "abandoned") {
    throw new AppError("Interview is already closed.", 400);
  }

  /*
   * -------------------------------------------------------
   * Finalization/payment is already in progress.
   *
   * Do NOT allow Quit to turn the interview into abandoned
   * while the completion flow is processing.
   *
   * This is especially important when paymentStatus is
   * "charging" or "charged".
   * -------------------------------------------------------
   */
  if (
    interview.finalizationKey ||
    interview.paymentStatus === "charging" ||
    interview.paymentStatus === "charged"
  ) {
    throw new AppError(
      "Interview finalization is already in progress. Please wait for it to complete.",
      409,
    );
  }

  interview.status = "abandoned";

  interview.endedAt = new Date();

  interview.terminationReason = "quit";

  interview.finalizationKey = null;

  await interview.save();

  return interview;
};

/*
 * =========================================================
 * INTERVIEW HISTORY
 * =========================================================
 */

export const getInterviewHistory = async (userId) => {
  return Interview.find({
    userId,
    status: "completed",
  }).sort({
    createdAt: -1,
  });
};

/*
 * =========================================================
 * DELETE INTERVIEW
 * =========================================================
 */

export const deleteInterview = async (userId, interviewId) => {
  validateInterviewId(interviewId);

  const interview = await findUserInterview(userId, interviewId);

  await Interview.deleteOne({
    _id: interview._id,
    userId,
  });

  return {
    interviewId,
  };
};
