/**
 * RIO Roadmap Knowledge Base
 *
 * This file contains:
 *
 * 1. Canonical knowledge factories
 * 2. Knowledge validation helpers
 * 3. Roadmap template registry
 *
 * Important:
 * - Knowledge is static/canonical.
 * - It is NOT generated by an LLM.
 * - User roadmaps are snapshots derived from this knowledge.
 * - The frontend never needs to understand the complete knowledge graph.
 */

/* -------------------------------------------------------------------------- */
/* Node Factory                                                               */
/* -------------------------------------------------------------------------- */

export const createKnowledgeNode = ({
  id,
  title,
  category,
  importance = "important",
  description = "",
  whyItMatters = "",
  prerequisites = [],
  enables = [],
  alternatives = [],
  related = [],
  guidance = {},
  practice = {},
  metadata = {},
}) => {
  if (!id) {
    throw new Error("Knowledge node requires an id.");
  }

  if (!title) {
    throw new Error(`Knowledge node "${id}" requires a title.`);
  }

  return {
    id,
    title,
    category,
    importance,

    description,
    whyItMatters,

    prerequisites,
    enables,
    alternatives,
    related,

    guidance: {
      beginner: guidance.beginner || "",
      alreadyKnown: guidance.alreadyKnown || "",
      partialKnowledge: guidance.partialKnowledge || "",
      nextStep: guidance.nextStep || "",
    },

    practice: {
      learn: practice.learn || [],
      practice: practice.practice || [],
      build: practice.build || [],
      validate: practice.validate || [],
    },

    metadata: {
      ...metadata,
    },
  };
};

/* -------------------------------------------------------------------------- */
/* Edge Factory                                                               */
/* -------------------------------------------------------------------------- */

export const createKnowledgeEdge = ({
  source,
  target,
  type = "recommended-next",
  reason = "",
}) => {
  if (!source || !target) {
    throw new Error("Knowledge edge requires source and target.");
  }

  return {
    source,
    target,
    type,
    reason,
  };
};

/* -------------------------------------------------------------------------- */
/* Roadmap Template Factory                                                   */
/* -------------------------------------------------------------------------- */

export const createRoadmapTemplate = ({
  id,
  version = 1,
  type = "role",
  title,
  description = "",
  goal = "",
  nodes = [],
  edges = [],
  alternatives = [],
  metadata = {},
}) => {
  if (!id) {
    throw new Error("Roadmap template requires an id.");
  }

  if (!title) {
    throw new Error(`Roadmap template "${id}" requires a title.`);
  }

  return {
    id,
    version,
    type,

    title,
    description,
    goal,

    nodes,
    edges,

    alternatives,

    metadata: {
      ...metadata,
    },
  };
};

/* -------------------------------------------------------------------------- */
/* Knowledge Validation                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Validates the basic integrity of a roadmap template.
 *
 * This validation intentionally stays lightweight.
 * More advanced graph validation belongs to the template service.
 */
export const validateRoadmapTemplate = (template) => {
  const errors = [];

  if (!template || typeof template !== "object") {
    return {
      valid: false,
      errors: ["Roadmap template must be an object."],
    };
  }

  if (!template.id) {
    errors.push("Template id is required.");
  }

  if (!template.title) {
    errors.push("Template title is required.");
  }

  if (!Array.isArray(template.nodes)) {
    errors.push("Template nodes must be an array.");
  }

  if (!Array.isArray(template.edges)) {
    errors.push("Template edges must be an array.");
  }

  if (Array.isArray(template.nodes)) {
    const nodeIds = new Set();

    for (const node of template.nodes) {
      if (!node?.id) {
        errors.push("Every roadmap node must have an id.");
        continue;
      }

      if (nodeIds.has(node.id)) {
        errors.push(`Duplicate roadmap node id: ${node.id}`);
      }

      nodeIds.add(node.id);
    }

    if (Array.isArray(template.edges)) {
      for (const edge of template.edges) {
        if (!edge?.source || !edge?.target) {
          errors.push("Every roadmap edge requires source and target.");
          continue;
        }

        if (!nodeIds.has(edge.source)) {
          errors.push(
            `Edge source "${edge.source}" does not exist in roadmap nodes.`,
          );
        }

        if (!nodeIds.has(edge.target)) {
          errors.push(
            `Edge target "${edge.target}" does not exist in roadmap nodes.`,
          );
        }
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
};

/* -------------------------------------------------------------------------- */
/* Knowledge Lookup Helpers                                                   */
/* -------------------------------------------------------------------------- */

export const findKnowledgeNode = (template, nodeId) => {
  if (!template || !Array.isArray(template.nodes)) {
    return null;
  }

  return template.nodes.find((node) => node.id === nodeId) || null;
};

export const getOutgoingEdges = (template, nodeId) => {
  if (!template || !Array.isArray(template.edges)) {
    return [];
  }

  return template.edges.filter((edge) => edge.source === nodeId);
};

export const getIncomingEdges = (template, nodeId) => {
  if (!template || !Array.isArray(template.edges)) {
    return [];
  }

  return template.edges.filter((edge) => edge.target === nodeId);
};

export const getPrerequisiteIds = (template, nodeId) => {
  return getIncomingEdges(template, nodeId)
    .filter((edge) => edge.type === "prerequisite")
    .map((edge) => edge.source);
};

/* -------------------------------------------------------------------------- */
/* Roadmap Registry                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Import canonical roadmap templates here.
 *
 * IMPORTANT:
 * This import is intentionally placed after the factories above because
 * roadmap files use createRoadmapTemplate/createKnowledgeNode internally.
 */

import frontendDeveloperRoadmap from "./roadmaps/frontend-developer/index.js";
import backendDeveloperRoadmap from "./roadmaps/backend-developer/index.js";
import cloudEngineerRoadmap from "./roadmaps/cloud-engineer/index.js";
import devopsPlatformEngineerRoadmap from "./roadmaps/devops-platform-engineer/index.js";
import dataEngineerRoadmap from "./roadmaps/data-engineer/index.js";
import aiMlEngineerRoadmap from "./roadmaps/ai-ml-engineer/index.js";
import genAiLlmEngineerRoadmap from "./roadmaps/gen-ai-llm-engineer/index.js";
import cybersecuritySecurityEngineerRoadmap from "./roadmaps/cybersecurity-security-engineer/index.js";
import fullStackDeveloperRoadmap from "./roadmaps/full-stack-developer/index.js";
import systemDesignSoftwareArchitectureRoadmap from "./roadmaps/system-design-software-architecture/index.js";

/**
 * Canonical roadmap registry.
 *
 * Every standard roadmap available to RIO is registered here.
 */
export const roadmapTemplates = {
  "frontend-developer": frontendDeveloperRoadmap,

  "backend-developer": backendDeveloperRoadmap,

  "cloud-engineer": cloudEngineerRoadmap,

  "devops-platform-engineer": devopsPlatformEngineerRoadmap,

  "data-engineer": dataEngineerRoadmap,

  "ai-ml-engineer": aiMlEngineerRoadmap,

  "gen-ai-llm-engineer": genAiLlmEngineerRoadmap,

  "cybersecurity-security-engineer": cybersecuritySecurityEngineerRoadmap,

  "full-stack-developer": fullStackDeveloperRoadmap,

  "system-design-software-architecture":
    systemDesignSoftwareArchitectureRoadmap,
};

/* -------------------------------------------------------------------------- */
/* Roadmap Registry Helpers                                                   */
/* -------------------------------------------------------------------------- */

export const getRoadmapTemplate = (roadmapId) => {
  if (!roadmapId) {
    return null;
  }

  return roadmapTemplates[roadmapId] || null;
};

export const getAllRoadmapTemplates = () => {
  return Object.values(roadmapTemplates);
};

export const hasRoadmapTemplate = (roadmapId) => {
  return Boolean(roadmapTemplates[roadmapId]);
};

/* -------------------------------------------------------------------------- */
/* Registry Validation                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Validate every registered roadmap during service startup.
 *
 * This catches broken node/edge references early instead of
 * discovering them after users start generating roadmaps.
 */
export const validateRoadmapRegistry = () => {
  const results = [];

  for (const roadmap of getAllRoadmapTemplates()) {
    const result = validateRoadmapTemplate(roadmap);

    results.push({
      roadmapId: roadmap.id,
      ...result,
    });
  }

  const invalid = results.filter((result) => !result.valid);

  return {
    valid: invalid.length === 0,
    results,
  };
};

/* -------------------------------------------------------------------------- */
/* Contract Version                                                           */
/* -------------------------------------------------------------------------- */

export const KNOWLEDGE_CONTRACT_VERSION = 1;

/* -------------------------------------------------------------------------- */
/* Default Export                                                             */
/* -------------------------------------------------------------------------- */

export default {
  createKnowledgeNode,
  createKnowledgeEdge,
  createRoadmapTemplate,

  validateRoadmapTemplate,

  findKnowledgeNode,
  getOutgoingEdges,
  getIncomingEdges,
  getPrerequisiteIds,

  roadmapTemplates,
  getRoadmapTemplate,
  getAllRoadmapTemplates,
  hasRoadmapTemplate,
  validateRoadmapRegistry,

  KNOWLEDGE_CONTRACT_VERSION,
};
